In [8]:
import pandas as pd

In [11]:
titanic = pd.read_csv("./z. pandas_titanic_data.csv")
titanic.head()

FileNotFoundError: [Errno 2] No such file or directory: './z1. pandas_titanic_data.csv'

In [12]:
air_quality = pd.read_csv("./z1. pandas_air_quality.csv")
air_quality.head()

,city,country,date.utc,location,parameter,value,unit
0,Antwerpen,BE,2019-06-18 06:00:00+00:00,BETR801,pm25,18.0,µg/m³
1,Antwerpen,BE,2019-06-17 08:00:00+00:00,BETR801,pm25,6.5,µg/m³
2,Antwerpen,BE,2019-06-17 07:00:00+00:00,BETR801,pm25,18.5,µg/m³
3,Antwerpen,BE,2019-06-17 06:00:00+00:00,BETR801,pm25,16.0,µg/m³
4,Antwerpen,BE,2019-06-17 05:00:00+00:00,BETR801,pm25,7.5,µg/m³

In [13]:
# Sort values

titanic.sort_values(by="Age").head()

titanic.sort_values(by=["Pclass", "Age"], ascending=False).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S

In [14]:
no2 = air_quality[air_quality["parameter"] == "no2"]

In [16]:
no2_subset = no2.sort_index().groupby(["location"]).head(2)
no2_subset

,city,country,date.utc,location,parameter,value,unit
1825,Paris,FR,2019-06-21 00:00:00+00:00,FR04014,no2,20.0,µg/m³
1826,Paris,FR,2019-06-20 23:00:00+00:00,FR04014,no2,21.8,µg/m³
3501,Antwerpen,BE,2019-06-17 08:00:00+00:00,BETR801,no2,41.0,µg/m³
3502,Antwerpen,BE,2019-06-17 07:00:00+00:00,BETR801,no2,45.0,µg/m³
3664,London,GB,2019-06-17 11:00:00+00:00,London Westminster,no2,11.0,µg/m³
3665,London,GB,2019-06-17 10:00:00+00:00,London Westminster,no2,11.0,µg/m³